# Generated by Django 2.2 on 2020-04-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Click on update profile to add more information about yourself a description about yourself!'),
            preserve_default=False,
        ),
    ]
