# Generated by Django 2.2 on 2020-04-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200401_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date',
            new_name='year',
        ),
    ]
