# Generated by Django 2.2 on 2020-04-23 23:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='art_2019'),
        ),
    ]
